/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // HSL component format so Tailwind opacity works: bg-primary/50 etc.
        bg: {
          0: 'hsl(var(--bg-0) / <alpha-value>)',
          1: 'hsl(var(--bg-1) / <alpha-value>)',
          2: 'hsl(var(--bg-2) / <alpha-value>)',
          3: 'hsl(var(--bg-3) / <alpha-value>)',
        },
        fg: {
          0: 'hsl(var(--fg-0) / <alpha-value>)',
          1: 'hsl(var(--fg-1) / <alpha-value>)',
          2: 'hsl(var(--fg-2) / <alpha-value>)',
          3: 'hsl(var(--fg-3) / <alpha-value>)',
          4: 'hsl(var(--fg-4) / <alpha-value>)',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
          soft: 'hsl(var(--primary-soft) / <alpha-value>)',
          foreground: 'hsl(var(--primary-foreground) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary) / <alpha-value>)',
          soft: 'hsl(var(--secondary-soft) / <alpha-value>)',
          foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)',
        },
        rose: 'hsl(var(--accent-rose) / <alpha-value>)',
        amber: 'hsl(var(--accent-amber) / <alpha-value>)',
        emerald: 'hsl(var(--accent-emerald) / <alpha-value>)',
        sky: 'hsl(var(--accent-sky) / <alpha-value>)',
        pink: 'hsl(var(--accent-pink) / <alpha-value>)',
        line: 'hsl(var(--line) / <alpha-value>)',
        'line-soft': 'hsl(var(--line-soft) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['var(--font-fira-code)', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
      },
      boxShadow: {
        glass: '0 12px 40px hsl(var(--bg-0) / 0.6), 0 0 0 1px hsl(var(--line) / 0.5)',
        'glass-sm': '0 4px 20px hsl(var(--bg-0) / 0.4), 0 0 0 1px hsl(var(--line) / 0.5)',
        'glass-lg': '0 24px 60px hsl(var(--bg-0) / 0.7), 0 0 0 1px hsl(var(--line) / 0.5)',
        'neon-primary': '0 0 16px hsl(var(--primary) / 0.5), 0 0 32px hsl(var(--primary) / 0.3)',
        'neon-secondary': '0 0 16px hsl(var(--secondary) / 0.5), 0 0 32px hsl(var(--secondary) / 0.3)',
        'neon-rose': '0 0 16px hsl(var(--accent-rose) / 0.5), 0 0 32px hsl(var(--accent-rose) / 0.3)',
        'neon-amber': '0 0 16px hsl(var(--accent-amber) / 0.5), 0 0 32px hsl(var(--accent-amber) / 0.3)',
        'neon-emerald': '0 0 16px hsl(var(--accent-emerald) / 0.5), 0 0 32px hsl(var(--accent-emerald) / 0.3)',
        'inner-glow': 'inset 0 1px 0 hsl(var(--fg-0) / 0.06), inset 0 -1px 0 hsl(var(--bg-0) / 0.5)',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'in-out-quart': 'cubic-bezier(0.76, 0, 0.24, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'emphasized': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      transitionDuration: {
        '400': '400ms',
        '600': '600ms',
        '800': '800ms',
        '1200': '1200ms',
        '1600': '1600ms',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, hsl(var(--primary)), hsl(var(--secondary)))',
        'gradient-aurora': 'linear-gradient(135deg, hsl(var(--primary)), hsl(var(--secondary)), hsl(var(--accent-rose)))',
        'gradient-aurora-soft': 'linear-gradient(135deg, hsl(var(--primary) / 0.2), hsl(var(--secondary) / 0.2), hsl(var(--accent-rose) / 0.2))',
        'gradient-mesh': 'radial-gradient(ellipse 80% 50% at 50% -20%, hsl(var(--primary) / 0.3), transparent), radial-gradient(ellipse 60% 50% at 80% 50%, hsl(var(--secondary) / 0.2), transparent), radial-gradient(ellipse 60% 50% at 20% 80%, hsl(var(--accent-rose) / 0.2), transparent)',
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      keyframes: {
        'fade-in':     { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-up':     { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-down':   { from: { opacity: '0', transform: 'translateY(-24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-left':  { from: { opacity: '0', transform: 'translateX(-32px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'slide-right': { from: { opacity: '0', transform: 'translateX(32px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'scale-in':    { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'float':       { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        'float-slow':  { '0%,100%': { transform: 'translate(0,0) rotate(0)' }, '50%': { transform: 'translate(0,-18px) rotate(2deg)' } },
        'blob':        { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '33%': { transform: 'translate(40px,-60px) scale(1.1)' }, '66%': { transform: 'translate(-30px,30px) scale(0.95)' } },
        'shimmer':     { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        'gradient-pan':{ '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        'aurora':      { '0%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' }, '100%': { backgroundPosition: '0% 50%' } },
        'spin-slow':   { from: { transform: 'rotate(0)' }, to: { transform: 'rotate(360deg)' } },
        'spin-reverse':{ from: { transform: 'rotate(0)' }, to: { transform: 'rotate(-360deg)' } },
        'twinkle':     { '0%,100%': { opacity: '0.2', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.3)' } },
        'glow-pulse':  { '0%,100%': { boxShadow: '0 0 14px hsl(var(--primary) / 0.3), 0 0 28px hsl(var(--primary) / 0.1)' }, '50%': { boxShadow: '0 0 28px hsl(var(--primary) / 0.7), 0 0 56px hsl(var(--primary) / 0.3)' } },
        'caret-blink': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        'orbit':       { from: { transform: 'rotate(0deg) translateX(0) rotate(0deg)' }, to: { transform: 'rotate(360deg) translateX(0) rotate(-360deg)' } },
        'ticker':      { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
        'ripple':      { '0%': { transform: 'scale(0)', opacity: '1' }, '100%': { transform: 'scale(4)', opacity: '0' } },
      },
      animation: {
        'fade-in':      'fade-in 0.6s ease-out both',
        'fade-up':      'fade-up 0.7s cubic-bezier(0.16,1,0.3,1) both',
        'fade-down':    'fade-down 0.7s cubic-bezier(0.16,1,0.3,1) both',
        'slide-left':   'slide-left 0.7s cubic-bezier(0.16,1,0.3,1) both',
        'slide-right':  'slide-right 0.7s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in':     'scale-in 0.5s cubic-bezier(0.34,1.56,0.64,1) both',
        'float':        'float 6s ease-in-out infinite',
        'float-slow':   'float-slow 8s ease-in-out infinite',
        'blob':         'blob 14s ease-in-out infinite',
        'shimmer':      'shimmer 2.2s linear infinite',
        'gradient-pan': 'gradient-pan 8s ease infinite',
        'aurora':       'aurora 12s ease infinite',
        'spin-slow':    'spin-slow 18s linear infinite',
        'spin-reverse': 'spin-reverse 24s linear infinite',
        'twinkle':      'twinkle 2.5s ease-in-out infinite',
        'glow-pulse':   'glow-pulse 3s ease-in-out infinite',
        'caret-blink':  'caret-blink 1s step-end infinite',
        'orbit':        'orbit 20s linear infinite',
        'ticker':       'ticker 30s linear infinite',
        'ripple':       'ripple 0.6s ease-out forwards',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
